class Emoji:
    OK = ":white_check_mark:"
    X = ":x:"
    WARNING = ":warning:"
    YARN = ":yarn:"
    ALARM_CLOCK = ":alarm_clock:"
    FILE_FOLDER = ":file_folder:"
    SCROLL = ":scroll:"
    BALLOT_BOX_WITH_CHECK = ":ballot_box_with_check:"
    MAILBOX_CLOSED = ":mailbox_closed:"
    MAILBOX_WITH_MAIL = ":mailbox_with_mail:"
    MUSICAL_SCORE = ":musical_score:"
    DIVIDERS = ":dividers:"
    CHECKERED_FLAG = ":checkered_flag:"
    INFORMATION_SOURCE = ":information_source:"
    EXCLAMATION = ":exclamation:"
    HEADPHONES = ":headphones:"
    SPACE_INVADER = ":space_invader:"
    MUSICAL_NOTE = ":musical_note:"
    POSTAL_HORN = ":postal_horn:"
    GAME_DIE = ":game_die:"
    LEVEL_SLIDER = ":level_slider:"
    DETECTIVE = ":detective:"


class UnicodeEmoji:
    OK = "✅"
    X = "❌"
    BALLOT_BOX_WITH_CHECK = "☑️"
    ARROW_LEFT = "⬅️"
    ARROW_RIGHT = "➡️"
    ARROW_BACKWARD = "◀️"
    ARROW_FORWARD = "▶️"
    STOP_BUTTON = "⏹️"
